src/dashboard/urls.py
from django.urls import path
from dashboard.views import *


app_name = "dashboard"

urlpatterns = [
    path("", dashboard_view, name='dashboard')
]

src/index/urls.py
from django.urls import path
from index import views

# URLS AQUIII

app_name = "home"


urlpatterns = [
    path("", views.home, name="home"),
    path("about", views.about, name="about"),
]

src/loja/urls.py
from django.urls import path
from loja import views


app_name = 'loja'

# urls AQUI


urlpatterns = [
    path('', views.lojaview, name='loja'),
    path('add-cart/<int:produto_id>/', views.add_cart, name='add-cart'),
    path('remove-cart/<int:produto_id>/', views.remove_cart, name='remove-cart'),
    path('remove-all-cart/<int:produto_id>', views.remove_all_cart, name='remove-all-cart'),
    path('tosa', views.tosa, name='tosa'),
    path('tosa/marcada', views.tosa_marcada, name='tosa_marcada'),
    path('banho', views.banho, name='banho'),
    path('banho/marcado', views.banho_marcado, name='banho_marcado'),
    path('remove-all-cart/<int:produto_id>', views.remove_all_cart, name='remove-all-cart'),
]

src/maindjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("index.urls")),
    path("usuarios/", include("usuarios.urls")),
    path("loja/", include("loja.urls")),
    path("admin/", admin.site.urls),
    path("dashboard/", include("dashboard.urls")),
    # path('dashboard', include("dashboard.urls")),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)  # snippet

# The above snippet tells Django where to find user-uploaded images when the project is still in the development stage.

src/usuarios/urls.py
from django.urls import path
from .views import *

# URLS AQUI

app_name = 'usuarios'

urlpatterns = [
    path('login', login_view, name='login'),
    path('login/logged-in', login_sucess, name="login_sucess"),
    path('usuario', user_view, name='usuario'),
    path('logout', logout_view, name='logout'),
    path('signup', signup, name='signup'),
    path('signup/sucess', signup_sucess_view, name='signupsucess'),
    path('atendimento', atendimento, name='atendimento'),
    path('atendimento/enviado', atendimentoSubmited, name='atendimento-enviado'),
    path('cart', cart_view, name='carrinho'),
]

src/index/templates/index/about.html
{% extends 'index/base.html' %} {% block title %} Meu Melhor Amigo {% endblock%} 
{% block content %} {% load static %}

<link rel="stylesheet" href="{% static 'index/style.css' %}" />
<div class="all">
  <div class="display-center">
    <h1>Sobre nos</h1>
    <div class="paragrafo">
      <p>
        <img class="FotoAbout" src="{% static 'index/fotoaboutsu.png' %}" alt="">
        
            No Petshop "Melhor Amigo", nós entendemos que seu animal de estimação é
          mais do que apenas um bichinho, é um membro especial da sua família. Com
          isso em mente, estamos comprometidos em fornecer cuidados excepcionais e
          serviços de alta qualidade para garantir que seu melhor amigo tenha uma
          vida feliz e saudável. <br> 
      </p>
      <p>
            Com uma equipe dedicada e apaixonada por animais,
          nossos profissionais treinados estão prontos para oferecer os melhores
          cuidados para o seu pet. Desde serviços de tosa profissional, onde
          deixaremos seu animalzinho com um visual impecável, até a limpeza e
          higienização completa, proporcionamos um ambiente seguro e tranquilo
          para que seu amigo se sinta confortável durante todo o processo. <br> 
      </p>
      <p>
            Sabemos que a alimentação é fundamental para a saúde do seu pet, por isso
          oferecemos uma ampla variedade de rações de alta qualidade e alimentos
          balanceados, adaptados às necessidades individuais de cada animal.
          Nossos especialistas estão disponíveis para fornecer orientação
          personalizada e ajudálo a escolher a melhor opção para o seu amiguinho. <br>
      </p>
      <p>
            No Petshop "Melhor Amigo", também acreditamos na importância da
          socialização e diversão para o bem-estar dos animais. Por isso,
          oferecemos momentos especiais de brincadeiras e interação em nosso
          espaço dedicado, garantindo que seu pet se divirta e faça novos amigos. <br>
      </p>
      <p>
            Além disso, temos uma ampla variedade de brinquedos e acessórios para
          enriquecer a vida do seu animalzinho. Nossa galeria de fotos é o reflexo
          do nosso amor e cuidado pelos animais. Lá, você poderá ver alguns dos
          adoráveis clientes que já passaram pelo nosso petshop. É um verdadeiro
          prazer atender a cada um deles e contribuir para o seu bem-estar e
          felicidade. <br>
      </p>
      <p>
            Estamos ansiosos para conhecê-lo e ao seu melhor amigo!
          Visite-nos no Petshop "Melhor Amigo" e descubra a diferença que fazemos
          na vida dos animais de estimação. Entre em contato conosco por telefone,
          e-mail ou através do nosso formulário de contato no nosso site. Seu pet merece o melhor, e nós
          estamos aqui para fornecer exatamente isso. Confie no Petshop "Melhor
          Amigo" para cuidar do seu melhor amigo como se fosse nosso próprio. <br>

      </p>
     
      <h4>
        Produtos ofertados pelo Petshop:
      </h4>
      <p> 
        1. Ração Premium: No Petshop "Melhor Amigo", oferecemos uma seleção
        de rações premium para cães e gatos. Essas rações são formuladas com
        ingredientes de alta qualidade, garantindo uma nutrição balanceada e
        adequada para o seu pet. Temos opções para diferentes idades, raças e
        necessidades específicas, proporcionando uma dieta saudável e saborosa
        para o seu melhor amigo.
        <br>
      </p>
      <p> 
        2. Serviço de Tosa Especializada: Proporcionamos serviços profissionais de
        tosa para cães de todas as raças. Nossos tosadores experientes e
        qualificados utilizam técnicas avançadas para garantir que seu pet tenha
        um visual impecável. Além de cortes de pelos personalizados, também
        realizamos higienização e cuidados especiais, como limpeza de ouvidos e
        corte de unhas, deixando seu cãozinho limpo e bem cuidado.
        <br>
      </p>
      <p>
        3. Banho Relaxante: No Petshop "Melhor Amigo", oferecemos banhos
        relaxantes para cães e gatos. Utilizamos produtos de qualidade, seguros
        e adequados para cada tipo de pelagem, garantindo uma limpeza
        profunda e refrescante. Nossos profissionais carinhosos proporcionam
        um ambiente tranquilo e seguro para que seu pet desfrute de um banho
        agradável, deixando-o com uma pelagem macia, brilhante e cheirosa.
        <br>
      </p>
      <p>
        4. Brinquedos Interativos: Valorizamos o enriquecimento e a diversão dos
        animais, por isso oferecemos uma variedade de brinquedos interativos.
        Esses brinquedos estimulam a mente e o corpo do seu pet, promovendo
        o exercício físico e mental. Desde brinquedos de mastigação duráveis até
        jogos interativos, temos opções para cães e gatos de todos os tamanhos
        e idades, garantindo horas de entretenimento e diversão saudável.
        <br>
      </p>
      <p>
        5. Produtos de Higiene e Cuidados: Na nossa seleção de produtos, você
        encontrará uma gama de itens de higiene e cuidados para o seu pet. Isso
        inclui shampoos e condicionadores específicos para diferentes tipos de
        pelagem, escovas e pentes para manter os pelos desembaraçados e
        saudáveis, produtos de limpeza auricular e ocular, além de acessórios
        essenciais como coleiras, guias e comedouros. Tudo o que você precisa
        para manter seu animalzinho limpo, confortável e bem cuidado.
        <br>
      </p>
      <p>
        Esses são apenas alguns dos produtos disponíveis no Petshop "Melhor Amigo".
        Temos um catálogo completo e diversificado, cuidadosamente selecionado para
        atender às necessidades dos animais de estimação. Nossa equipe terá prazer 
      </p>
    </div>
  </div>
</div>
{% endblock %}

src/index/templates/index/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    {% load static %}
    <link
      rel="shortcut icon"
      href="{% static 'index/favicon.ico' %}"
      type="image/x-icon"
    />
    <link rel="stylesheet" href="{% static 'index/style.css' %}" />
    <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
    crossorigin="anonymous"
    />
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
    integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
    crossorigin="anonymous"
    referrerpolicy="no-referrer"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
      crossorigin="anonymous"
    ></script>
    <title>{% block title %} Default title {% endblock %}</title>
</head>
<body>
    <header>
      <div class="top-container">
        <div class="top-bar">
          <!--   Home/home -->
          <a href="{% url 'home:home' %}">
            home <i class="fa-solid fa-house"></i
              ></a>
              <!-- ABOUT US-->
              <a href="{% url 'home:about' %}"> sobre nos <i class="fa-solid fa-address-card"></i></a>
              <!-- Contact us-->
              <a href="{% url 'usuarios:atendimento'%}">
                atendimento <i class="fa-solid fa-envelope"></i>
              </a>
              {% if request.user.is_admin == True %}
              <a href="{% url 'dashboard:dashboard' %}">
                dashb.   <i class="fa-solid fa-chart-line"></i>
              </a>
              <a href="http://127.0.0.1:8000/admin/">
                admin <i class="fa-solid fa-lock"></i>
              </a>
              {% endif %}
            </div>
          </div>
          <nav class="navnav">
            
            <div>
              <a href="">
                <img             
                src="{% static 'index/logosmall.png' %}"
                alt="iconeoprincipal"
                height="100px"
                />
              </a>
            </div>
            <button class="hamburguer">
              <span class="bar"></span>
              <span class="bar"></span>
              <span class="bar"></span>
            </button>              
      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Tosa</button>
        <ul class="dropdown-menu">
          <li><a href="http://127.0.0.1:8000/loja/tosa" class="dropdown-item">Cães&raquo;</a>
            <ul class="dropdown-menu dropdown-submenu">
              <li><a href="http://127.0.0.1:8000/loja/tosa" class="dropdown-item">Porte Grande</a></li>
              <li><a href="http://127.0.0.1:8000/loja/tosa" class="dropdown-item">Porte Médio</a></li>
              <li><a href="http://127.0.0.1:8000/loja/tosa" class="dropdown-item">Porte Pequeno</a></li>
            </ul>
          </li>
        </ul>
      </div>
      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Banho</button>
        <ul class="dropdown-menu">
          <li><a href="{% url 'loja:banho' %}" class="dropdown-item">Cães&raquo;</a>
            <ul class="dropdown-menu dropdown-submenu">
              <li><a href="{% url 'loja:banho' %}" class="dropdown-item">Porte Grande</a></li>
              <li><a href="{% url 'loja:banho' %}" class="dropdown-item">Porte Médio</a></li>
              <li><a href="{% url 'loja:banho' %}" class="dropdown-item">Porte Pequeno</a></li>
            </ul>
          </li>
          <li><a href="{% url 'loja:banho' %}" class="dropdown-item">Felinos&raquo;</a>
            <ul class="dropdown-menu dropdown-submenu">
              <li><a href="{% url 'loja:banho' %}" class="dropdown-item">Porte Médio</a></li
              <li><a href="{% url 'loja:banho' %}" class="dropdown-item">Porte Pequeno</a></li>
            </ul>
          </li>
        </ul>
      </div>
      <div class="dropdown">
        <a href="{% url 'loja:loja' %}"><button class="btn btn-primary" style="background-color: #45d045; border: none;">Shop</button></a>
      </div>

      <ul class="nav-menu"> 
        <li class="Nav-item"><a href="{% url 'loja:loja' %}">Shop</a></li>
        <li class="Nav-item"><a href="{% url 'usuarios:login' %}" >
          <i class="fa-regular fa-user"></i></a></li>
        <li class="Nav-item"><a href="{% url 'usuarios:carrinho' %}"> 
          <i class="fa-solid fa-bag-shopping"></i></a></li>
      </ul>
        <div class="nav-icons">
          <a href="{% url 'usuarios:login' %}" class="nav-icon">
            <i class="fa-regular fa-user"></i
              ></a>
              <a href="{% url 'usuarios:carrinho' %}" class="nav-icon">
                <i class="fa-solid fa-bag-shopping"></i
                  ></a>
        </div>
      </nav>
    </header>
            
            <script src="{% static 'index/script.js'  %}"></script>
            {% block content %} {% endblock %}
    <hr />
  </body>

  
  <footer class="pedosite">
    <div>
      <address>
        R. Melhores Amigos, 333 - Savassi <br />
        Belo Horizonte - MG, 3333333-333
      </address>
      <p>(31)-999999-9999</p>
      <div class="emailcontainer">
        <i class="fa-solid fa-envelope"></i>
        <span>meumelhoramigopetshop@melhor.amigo.com.br</span>
        <button><i class="fa-regular fa-copy"></i></button>
        <div>
          <a href="https://www.bcb.gov.br/estabilidadefinanceira/pix" target="_blank" >
            <img src="{% static 'index/pix.png'%}" alt="Aceitamos pix">
          </a>
        </div>
      </div>
    </div>
    <div class="author">
      Author: Diego Cheib / Roberto Fernandino <br />
      &copy; Copyright Reserved <br />
      <div class="emailcontainer">
        <i class="fa-solid fa-envelope"></i>
        <span> diegocheib@gmail.com</span>
        <button><i class="fa-regular fa-copy"></i></button>
      </div>
      <div class="emailcontainer">
        <i class="fa-solid fa-envelope"></i>
        <span> romfernandno@gmail.com </span>
        <button><i class="fa-regular fa-copy"></i></button>
      </div>
    </div>
  </footer>
</html>

src/index/templates/index/base2.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    {% load static %}
    <link
      rel="shortcut icon"
      href="{% static 'index/favicon.ico' %}"
      type="image/x-icon"
    />
    <link rel="stylesheet" href="{% static 'index/style.css' %}" />
    <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
    crossorigin="anonymous"
    />
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
    integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
    crossorigin="anonymous"
    referrerpolicy="no-referrer"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
      crossorigin="anonymous"
    ></script>
    <title>{% block title %} Default title {% endblock %}</title>
</head>
<body>
    <header>
      <div class="top-container">
        <div class="top-bar">
          <!--   Home/home -->
          <a href="{% url 'home:home' %}">
            home <i class="fa-solid fa-house"></i
              ></a>
              {% if request.user.is_admin == True %}
              <a href="{% url 'dashboard:dashboard' %}">
                dashboard <i class="fa-solid fa-chart-line"></i>
              </a>
              <a href="http://127.0.0.1:8000/admin/">
                admin panel <i class="fa-solid fa-lock"></i>
              </a>
              {% endif %}
            </div>
          </div>
        </header>
          <script src="{% static 'index/script.js'  %}"></script>
            {% block content %} {% endblock %}
    <hr />
  </body>

  
  <footer class="pedosite">
    <div>
      <address>
        R. Melhores Amigos, 333 - Savassi <br />
        Belo Horizonte - MG, 3333333-333
      </address>
      <p>(31)-999999-9999</p>
      <div class="emailcontainer">
        <i class="fa-solid fa-envelope"></i>
        <span>meumelhoramigopetshop@melhor.amigo.com.br</span>
        <button><i class="fa-regular fa-copy"></i></button>
        <div>
          <a href="https://www.bcb.gov.br/estabilidadefinanceira/pix" target="_blank" >
            <img src="{% static 'index/pix.png'%}" alt="Aceitamos pix">
          </a>
        </div>
      </div>
    </div>
    <div class="author">
      Author: Diego Cheib / Roberto Fernandino <br />
      &copy; Copyright Reserved <br />
      <div class="emailcontainer">
        <i class="fa-solid fa-envelope"></i>
        <span> diegocheib@gmail.com</span>
        <button><i class="fa-regular fa-copy"></i></button>
      </div>
      <div class="emailcontainer">
        <i class="fa-solid fa-envelope"></i>
        <span> romfernandno@gmail.com </span>
        <button><i class="fa-regular fa-copy"></i></button>
      </div>
    </div>
  </footer>
</html>

src/index/templates/index/index.html
{% extends 'index/base.html' %} {% block title %} Melhor Amigo {% endblock%} 
{% block content %} {% load static %}
<link rel="stylesheet" href="{%  static 'index/style.css' %}" />
<div class="all">
  <div class="title">
    <div class="slogan">
      <img src="{% static 'index/sloganpetshop.png' %}" alt="Imagem Slogan" />
    </div>
  </div>
  <div class="slide-carrousel">
    <div
      id="carouselExampleIndicators"
      class="carousel slide"
      data-bs-ride="carousel"
    >
      <div class="carousel-indicators">
        <button
          type="button"
          data-bs-target="#carouselExampleIndicators"
          data-bs-slide-to="0"
          class="active"
          aria-current="true"
          aria-label="Slide 1"
        ></button>
        <button
          type="button"
          data-bs-target="#carouselExampleIndicators"
          data-bs-slide-to="1"
          aria-label="Slide 2"
        ></button>
        <button
          type="button"
          data-bs-target="#carouselExampleIndicators"
          data-bs-slide-to="2"
          aria-label="Slide 3"
        ></button>
        <button
          type="button"
          data-bs-target="#carouselExampleIndicators"
          data-bs-slide-to="3"
          aria-label="Slide 4"
        ></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active" data-bs-interval="3000">
          <img
            src='{% static "index/foto1.png" %}'
            class="d-block w-100"
            alt="Foto de animais"
          />
        </div>
        <div class="carousel-item" data-bs-interval="3000">
          <img
            src='{% static "index/foto2.png" %}'
            class="d-block w-100"
            alt="Foto de animais"
          />
        </div>
        <div class="carousel-item" data-bs-interval="3000">
          <img
            src='{% static "index/foto3.png" %}'
            class="d-block w-100"
            alt="Foto de animais"
          />
        </div>
        <div class="carousel-item" data-bs-interval="3000">
          <img
            src='{% static "index/foto4.png" %}'
            class="d-block w-100"
            alt="Foto de animais"
          />
        </div>
      </div>
      <button
        class="carousel-control-prev"
        type="button"
        data-bs-target="#carouselExampleIndicators"
        data-bs-slide="prev"
      >
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button
        class="carousel-control-next"
        type="button"
        data-bs-target="#carouselExampleIndicators"
        data-bs-slide="next"
      >
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>
</div>
{% endblock %}