src/loja/urls.py
from django.urls import path
from loja import views


app_name = 'loja'

# urls AQUI


urlpatterns = [
    path('', views.lojaview, name='loja'),
    path('add-cart/<int:produto_id>/', views.add_cart, name='add-cart'),
    path('remove-cart/<int:produto_id>/', views.remove_cart, name='remove-cart'),
    path('remove-all-cart/<int:produto_id>', views.remove_all_cart, name='remove-all-cart'),
    path('tosa', views.tosa, name='tosa'),
    path('tosa/marcada', views.tosa_marcada, name='tosa_marcada'),
    path('banho', views.banho, name='banho'),
    path('banho/marcado', views.banho_marcado, name='banho_marcado'),
    path('remove-all-cart/<int:produto_id>', views.remove_all_cart, name='remove-all-cart'),
]

src/maindjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("index.urls")),
    path("usuarios/", include("usuarios.urls")),
    path("loja/", include("loja.urls")),
    path("admin/", admin.site.urls),
    path("dashboard/", include("dashboard.urls")),
    # path('dashboard', include("dashboard.urls")),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)  # snippet

# The above snippet tells Django where to find user-uploaded images when the project is still in the development stage.

src/usuarios/urls.py
from django.urls import path
from .views import *

# URLS AQUI

app_name = 'usuarios'

urlpatterns = [
    path('login', login_view, name='login'),
    path('login/logged-in', login_sucess, name="login_sucess"),
    path('usuario', user_view, name='usuario'),
    path('logout', logout_view, name='logout'),
    path('signup', signup, name='signup'),
    path('signup/sucess', signup_sucess_view, name='signupsucess'),
    path('atendimento', atendimento, name='atendimento'),
    path('atendimento/enviado', atendimentoSubmited, name='atendimento-enviado'),
    path('cart', cart_view, name='carrinho'),
]

src/loja/models.py
import stripe
from django.db import models
from loja.funcs import product_image_path
from maindjango.settings import STRIPE_PUBLIC_KEY
from django.apps import apps
import sqlite3

stripe.api_key = STRIPE_PUBLIC_KEY


# Create your models here.


class Category(models.Model):
    nome = models.CharField(max_length=60, default=None, blank=False, null=False)

    def __str__(self) -> str:
        return f"{self.nome}"

    class Meta:
        verbose_name_plural = "Categorias Produtos"


class Produto(models.Model):
    nome = models.CharField(max_length=50, default="Produto", unique=True)
    preco = models.IntegerField(default=0)  # cents
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    descricao = models.TextField()
    img = models.ImageField(upload_to=product_image_path)
    estoque = models.IntegerField(default=0, null=False, blank=False)

    def preco_em_real(self):
        return f"{(self.preco) / 100 }"

    def __str__(self) -> str:
        return f"{self.nome}| Cat:{self.category} | R${(self.preco)/100}"


class porte(models.Model):
    porte = models.CharField(default=None, blank=False, null=True, max_length=30)

    def __str__(self) -> str:
        return f"{self.porte}"


class TosaType(models.Model):
    name = models.CharField(default=None, blank=False, null=False, max_length=30)
    preco = models.FloatField()
    porte = models.ForeignKey(porte, on_delete=models.DO_NOTHING, null=True)

    def __str__(self) -> str:
        return f"{self.name} {self.porte} R${self.preco}"
    class Meta:
        verbose_name_plural = 'Categorias Tosa'


class BanhoType(models.Model):
    name = models.CharField(default=None, blank=False, null=False, max_length=30)
    preco = models.FloatField()
    porte = models.ForeignKey(porte, on_delete=models.DO_NOTHING, null=True)

    def __str__(self) -> str:
        return f"{self.name} {self.porte} R${self.preco}"
    
    class Meta:
        verbose_name_plural = 'Categorias Banho'


class Banho(models.Model):
    user = models.ForeignKey(
        "usuarios.Account",
        on_delete=models.CASCADE,
        blank=False,
        null=True,
        related_name="banho",
    )
    marcado = models.DateTimeField(auto_now_add=True)
    pet = models.CharField(max_length=30, default=None, blank=False, null=True)
    type = models.ForeignKey(BanhoType, on_delete=models.CASCADE)
    data = models.DateTimeField(unique=True)

class Tosa(models.Model):
    user = models.ForeignKey(
        "usuarios.Account",
        on_delete=models.CASCADE,
        blank=False,
        null=True,
        related_name="tosa",
    )
    marcado = models.DateTimeField(auto_now_add=True)
    pet = models.CharField(default=None, max_length=30, blank=False, null=True)
    type = models.ForeignKey(TosaType, on_delete=models.CASCADE)
    data = models.DateTimeField(unique=True)

src/loja/forms.py
from django import forms
from .models import Tosa, Banho

class TosaForm(forms.ModelForm):
    pet = forms.CharField(max_length=30,
                          min_length=3,
                          widget=forms.TextInput(attrs={
                              'class': "input-field",
                              'name': 'pet',
                              'required': True,
                              "maxlength": "30",
                              "minlength": '3',
                          }))
    
    data = forms.DateTimeField(input_formats=['%H:%M %d/%m/%Y'], widget=forms.DateTimeInput(attrs={
        "type": 'datetime-local',
        'name': 'data',
        'required': True,
        'class': 'date-input-field',
    }))
    class Meta:
        model = Tosa
        fields = ['pet', 'data']


class BanhoForm(forms.ModelForm):
    pet = forms.CharField(max_length=30,
                          min_length=3,
                          widget=forms.TextInput(attrs={
                              'class': 'input-field',
                              'required': True,
                              'name': "pet",
                              'maxlength': "30",
                              "min length":'3',
                          }))
    data = forms.DateTimeField(input_formats=['%H %M %d/%m/%Y'],
                               widget=forms.DateTimeInput(attrs={
                                   "type": 'datetime-local',
                                   "name": "data",
                                   "required": True,
                                   'class': 'date-input-field',
                               }))
    class Meta:
        model = Banho
        fields = ['pet', 'data']

src/loja/views.py
from django.shortcuts import render, redirect
from loja.models import Produto, Category, TosaType, BanhoType, Banho, Tosa
from django.http import HttpResponseRedirect
import stripe
from loja.forms import TosaForm, BanhoForm
from maindjango.settings import STRIPE_PUBLIC_KEY
from loja.funcs import SearchProductsToPaymentGateway
from usuarios.models import UserCart, UserCartItems
from django.contrib.auth.decorators import login_required

# stripe api key
stripe.api_key = STRIPE_PUBLIC_KEY


# Create your views here.
def lojaview(request, *args, **kwargs):
    produtos = Produto.objects.all()
    categorias = Category.objects.all()

    # category filter
    categoria_id = request.GET.get("categoria")
    if categoria_id:
        produtos = produtos.filter(category=categoria_id)

    # nome filter
    nome = request.GET.get("nome")
    if nome:
        produtos = produtos.filter(nome__icontains=nome)

    # filtra por preco maximo
    preco_max = request.GET.get("preco_max")
    if preco_max:
        produtos = produtos.filter(preco__lte=float(preco_max) * 100)

    return render(
        request,
        "loja/loja.html",
        {
            "produtos": produtos,
            "categorias": categorias,
            "nome": nome,
            "preco": preco_max,
        },
    )


@login_required
def add_cart(request, produto_id):
    produto = Produto.objects.get(pk=produto_id)
    cart, _ = UserCart.objects.get_or_create(user=request.user)
    cart_item, created = UserCartItems.objects.get_or_create(cart=cart, produto=produto)
    quantidade = int(request.POST.get("quantidade", 1))
    produto.estoque -= quantidade
    produto.save()
    if not created:
        cart_item.quantidade += quantidade
    else:
        cart_item.quantidade = quantidade

    cart_item.save()
    return HttpResponseRedirect(request.META.get("HTTP_REFERER", "/"))


@login_required
def remove_cart(request, produto_id):
    produto = Produto.objects.get(pk=produto_id)
    cart, _ = UserCart.objects.get_or_create(user=request.user)
    cart_items = UserCartItems.objects.get(cart=cart, produto=produto)
    quantidade = int(request.POST.get("quantidade", 1))
    if quantidade == cart_items.quantidade:
        cart_items.delete()
    else:
        produto.estoque += quantidade
        cart_items.quantidade -= quantidade
        produto.save()
        cart_items.save()
    return HttpResponseRedirect(request.META.get("HTTP_REFERER", "/"))


@login_required
def remove_all_cart(request, produto_id):
    produto = Produto.objects.get(pk=produto_id)
    cart = UserCart.objects.get(user=request.user)
    cart_items = UserCartItems.objects.get(cart=cart, produto=produto)
    cart_items.delete()
    return HttpResponseRedirect(request.META.get("HTTP_REFERER", "/"))


@login_required
def create_checkout_session():
    def post(self, *args, **kwargs):
        stripe.checkout.Session.create(
            payment_method_types=["card"],
            sucess_url="",
            line_items=[
                {
                    "price_data": {
                        "currency": "brl",
                    }
                }
            ],
        )


@login_required
def tosa(request):
    categorias = TosaType.objects.all()
    categorias_banho = BanhoType.objects.all()
    usuario = request.user
    if request.method == "POST":
        tosa_form = TosaForm(request.POST)
        tosa_id = request.POST.get("tosa-type")
        tosa_instance = TosaType.objects.get(pk=tosa_id)
        banho_form = (
            BanhoForm(request.POST) if request.POST.get("banho") == "on" else None
        )

        if tosa_form.is_valid():
            tosa = tosa_form.save(commit=False)
            nome_pet = tosa_form.cleaned_data["pet"]
            data = tosa_form.cleaned_data["data"]
            tosa.user = usuario
            tosa.type = tosa_instance
            tosa.save()

            if banho_form and banho_form.is_valid():
                banho_id = request.POST.get("banho-type")
                banho_instance = BanhoType.objects.get(pk=banho_id)
                banho = banho_form.save(commit=False)
                banho.user = usuario
                banho.type = banho_instance
                banho.data = data
                banho.pet = nome_pet
                banho.save()

        return redirect("loja:tosa_marcada")

    tosa_form = TosaForm()
    banho_form = BanhoForm()
    context = {
        "categorias": categorias,
        "categorias_banho": categorias_banho,
        "form": tosa_form,
        "banhoform": banho_form,
    }
    return render(request, "loja/tosa.html", context)


@login_required
def tosa_marcada(request):
    return render(request, "loja/tosamarcada.html")


@login_required
def banho(request):
    categorias = BanhoType.objects.all()
    categorias_tosa = TosaType.objects.all()
    usuario = request.user
    if request.method == "POST":
        banho_form = BanhoForm(request.POST)
        tosa_form = TosaForm(request.POST) if request.POST.get("tosa") == "on" else None
        banho_id = request.POST.get("banho-type")
        banho_instance = BanhoType(pk=banho_id)

        if banho_form.is_valid():
            banho = banho_form.save(commit=False)
            nome_pet = banho_form.cleaned_data["pet"]
            data = banho_form.cleaned_data["data"]
            banho.user = usuario
            banho.type = banho_instance
            banho.save()

            if tosa_form and tosa_form.is_valid():
                tosa_id = request.POST.get("tosa-type")
                tosa_instance = TosaType.objects.get(pk=tosa_id)
                tosa = tosa_form.save(commit=False)
                tosa.pet = nome_pet
                tosa.user = usuario
                tosa.type = tosa_instance
                tosa.data = data
                tosa.save()

            return redirect("loja:banho_marcado")

    banho_form = BanhoForm()

    context = {
        "categorias": categorias,
        "form": banho_form,
        "categorias_tosa": categorias_tosa,
    }
    return render(request, "loja/banho.html", context)


@login_required
def banho_marcado(request):
    return render(request, "loja/banhomarcado.html")

src/loja/templates/loja/banho.html
{% extends 'index/base.html' %}
{% block title %} Banho {% endblock %}
{% block content %}
{% load static %}
<script>
    document.addEventListener('DOMContentLoaded', (event) => {
        const tosaCheckBox = document.querySelector('.tosa-checkbox');
        const tosaOptions = document.getElementById('tosa-options');

        tosaCheckBox.addEventListener('change', (event) => {
            if (event.target.checked){
                tosaOptions.style.display = 'block';
            }
            else {
                tosaOptions.style.display = 'none';
            }
        });
    });
</script>

<link rel="stylesheet" href="{% static 'usuarios/style.css' %}">
<div class="atendimento-container">
    <h1 class="top-title">Banho</h1>
    <div class="information-container">
        <h4>Marque o cuidadoso Banho do seu pet aqui</h4>
    </div>
    {% if form.errors %}
        <div class="message">
            <div class="alert alert-danger" style="margin-bottom: 70px;">
                {{ form.errors }}</div>
        </div>
    {% endif %}
    <div class="atendimento-form-container">
        <form action="{% url 'loja:banho' %}" method="post">
            {% csrf_token %}
            <div class="input">
                <label for="banho-type">Banho:</label> <br>
                <select name="banho-type" class="select-input">
                    {% for categoria in categorias %}
                    <option value="{{categoria.id}}">{{categoria}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="input">
                {{ form.pet }}
                <label class="input-label" for="pet" ><span>Nome Pet</span></label>
            </div>
            <div class="input">
                <label for="data"><span>Data e Horario</span></label>
                {{ form.data }}
            </div>
            <div class="input">
                <label for="tosa">Deseja marcar uma tosa para seu pet de uma vez?</label> <br>
                <input type="checkbox" id="tosa" name="tosa" class="tosa-checkbox">
            </div>
            <div id="tosa-options" style="display: none;">
                <div class="input">
                    <label for="tosa-type">Tosa</label>
                    <select name="tosa-type" class="select-input">
                        {% for categoria in categorias_tosa %}
                        <option value="{{categoria.id}}">{{categoria}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <button type="submit" class="SubmitButton">Marcar</button>
        </form>
    </div>
</div>



{% endblock %}

src/loja/templates/loja/banhomarcado.html
{% extends 'index/base.html' %}

{% block title %} Bem vindo de volta!{% endblock %}
{% block content %} 
{% load static %}

<link rel="stylesheet" href="{% static 'usuarios/style.css' %}">
<div class="form-container">
    <div class="alert alert-success">{{ request.user.username }} seu Banho foi marcado com sucesso! 
        <a href="{% url 'usuarios:usuario' %}">
            clique aqui
        </a> 
        para conferir
    </div>
</div>
    

{% endblock %} 

src/loja/templates/loja/loja.html
{% extends 'index/base.html' %} {% block title %} Shop {% endblock %} 
{% block content %}
{% load static %} 
<hr>  
{% load my_filters %}
<link rel="stylesheet" href="{% static 'loja/style.css' %}" />
<div class="container">
  <form  method="get" action="{% url 'loja:loja'%}" class="shopform">
    <label for="categoria">Categoria:</label>
    <select name="categoria" class="categoria">
      <option value="">Todas</option>
      {% for categoria in categorias %}
      <option value="{{ categoria.id }}">{{ categoria.nome }}</option>
      {% endfor %}
    </select>
    <label for="preco">Preco Maximo:</label>
    <input type="number" name="preco_max" step="0.1" class="input">
    <label for="nome">Nome:</label>
    <input type="text" name="nome" class="input">
    <button type="submit" class="filterbutton">Filtrar</button>
  </form>
  <h2>Produtos</h2>
  <div class="row">
    {% if produtos %}
    {% for produto in produtos %}
    <div class="col-md-3">
      <div class="card">
        <img
          src="{{ produto.img.url }}"
          alt="{{ produto.nome }}"
          class="card-img-top"
        />
        <div class="card-body">
          <h5 class="card-title">{{ produto.nome }}</h5>
          <p class="card-text">{{ produto.descricao }}</p>
          <p class="card-price">R$ {{ produto.preco_em_real }}</p>
          <form method="post" action="{% url 'loja:add-cart' produto.id %}">
            {% csrf_token %}
            {% if produto.estoque != 0 %}
            <select name="quantidade" class="quantidade">
                {% for qtd in produto.estoque|times %}
                <option value="{{ qtd }}">{{ qtd }}</option>
                {% endfor %}
              </select>
            {% else %}
            <p> Sem estoque </p>
            {% endif %}
            <button type="submit" class="add-to-cart"> <i class="fa-solid fa-cart-shopping"></i></button>
          </form>
        </div>
      </div>
    </div>
    {% endfor %}
    {% else %}
    <div>
      <h5>Produto nao encontrado {% if nome %} <strong>{{ nome }}</strong> {% endif %}  {% if preco %} Nenhum produto com valor menor a R${{ preco }} {% endif %}</h5>
    </div>
  {% endif %}
  </div>
</div>
{% endblock %}

src/loja/templates/loja/produto.html
{% extends 'index/base.html' %}

{% block content %} {% load static %}
<link rel="stylesheet" href="{% static 'loja/style.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
{% load static %}
<body>

</body>




{% endblock %}

src/loja/templates/loja/tosa.html
{% extends 'index/base.html'%}
{% block title %} Tosa {% endblock %}
{% block content %}
{% load static %}
<script>
    document.addEventListener('DOMContentLoaded', (event) => {
        const banhoCheckbox = document.querySelector('.banho-checkbox');
        const banhoOptions = document.getElementById('banho-options');
        
        banhoCheckbox.addEventListener('change', (event) => {
            if (event.target.checked){
                banhoOptions.style.display = 'block';
            }
            else {
                banhoOptions.style.display = 'none';
            }
        });

    });
</script>
<link rel="stylesheet" href="{% static 'usuarios/style.css' %}">
<div class="atendimento-container">
    <h1 class="top-title">Tosa</h1>
    <div class="information-container">
        <h4>Marque a tosa do seu pet aqui</h4>
    </div>
    {% if form.errors %}
    <div class="message">
        <div class="alert alert-danger" style="margin-bottom: 70px;">
        {{ form.errors  }}
        </div>
    </div>
    {% endif %}
    <div class="atendimento-form-container">
        <form action="{% url 'loja:tosa' %}" method='post'>
        {% csrf_token %}
        <div class="input">
            <label for="tosa-type">Tosa</label><br>
            <select name="tosa-type" class="select-input"> 
                {% for categoria in categorias %}
                <option value="{{ categoria.id }}">{{categoria}}</option>
                {% endfor %}
            </select>
        </div>
        <div class="input">
            {{ form.pet }}
            <label  class="input-label" for="pet"><span>Nome Pet</span></label>
        </div>
        <div class="input">
            <label for="data"><span>Marque um Horario</span></label>
            {{ form.data }}
        </div>
        <div class="input">
            <label for="banho">Deseja marcar um banho para seu pet de uma vez?</label> <br>
            <input type="checkbox" id="banho" name="banho" class="banho-checkbox">
        </div>
        <div id="banho-options" style="display: none;">
            <div class="input">
                <label for="banho-type">Banho</label> <br>
                <select name="banho-type" class="select-input">
                    {% for categoria in categorias_banho %}
                    <option value="{{ categoria.id }}">{{ categoria }}</option>
                    {% endfor %}
                </select>            
            </div>
        </div>
        <button type="submit" class="SubmitButton">Marcar</button>
        </form>
    </div>
</div>
{% endblock %}

src/loja/templates/loja/tosamarcada.html
{% extends 'index/base.html' %}

{% block title %} Bem vindo de volta!{% endblock %}
{% block content %} 
{% load static %}

<link rel="stylesheet" href="{% static 'usuarios/style.css' %}">
<div class="form-container">
    <div class="alert alert-success">{{ request.user.username }} sua tosa foi marcado com sucesso! 
        <a href="{% url 'usuarios:usuario' %}">
            clique aqui
        </a> 
        para conferir
    </div>
</div>
    

{% endblock %} 