src/loja/urls.py
from django.urls import path
from loja import views


app_name = 'loja'

# urls AQUI


urlpatterns = [
    path('', views.lojaview, name='loja'),
    path('add-cart/<int:produto_id>/', views.add_cart, name='add-cart'),
    path('remove-cart/<int:produto_id>/', views.remove_cart, name='remove-cart'),
    path('remove-all-cart/<int:produto_id>', views.remove_all_cart, name='remove-all-cart'),
    path('tosa', views.tosa, name='tosa'),
    path('tosa/marcada', views.tosa_marcada, name='tosa_marcada'),
    path('banho', views.banho, name='banho'),
    path('banho/marcado', views.banho_marcado, name='banho_marcado'),
    path('remove-all-cart/<int:produto_id>', views.remove_all_cart, name='remove-all-cart'),
]

src/maindjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("index.urls")),
    path("usuarios/", include("usuarios.urls")),
    path("loja/", include("loja.urls")),
    path("admin/", admin.site.urls),
    path("dashboard/", include("dashboard.urls")),
    # path('dashboard', include("dashboard.urls")),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)  # snippet

# The above snippet tells Django where to find user-uploaded images when the project is still in the development stage.

src/usuarios/urls.py
from django.urls import path
from .views import *

# URLS AQUI

app_name = 'usuarios'

urlpatterns = [
    path('login', login_view, name='login'),
    path('login/logged-in', login_sucess, name="login_sucess"),
    path('usuario', user_view, name='usuario'),
    path('logout', logout_view, name='logout'),
    path('signup', signup, name='signup'),
    path('signup/sucess', signup_sucess_view, name='signupsucess'),
    path('atendimento', atendimento, name='atendimento'),
    path('atendimento/enviado', atendimentoSubmited, name='atendimento-enviado'),
    path('cart', cart_view, name='carrinho'),
]

src/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from loja.models import Produto

# Create your models here.


# Status atendimentos

STATUS_CHOISES = [
    ("p", "Pendente"),
    ("r", "Respondida"),
]


class Atendimentos(models.Model):
    nome = models.CharField(max_length=30)
    email = models.EmailField(max_length=150)
    phone = models.CharField(max_length=13, default=None, blank=False, null=True)
    assunto = models.CharField(max_length=40, blank=False, null=True)
    message = models.TextField(null=True, blank=False)
    is_newsletter = models.BooleanField(default=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOISES, default="p")
    data = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"Nome: {self.nome} -- Assunto: {self.assunto}  -- Status: {self.get_status_display()}"


class EmailErrorsLog(models.Model):
    email = models.EmailField(max_length=150)
    log = models.CharField(max_length=255, blank=False, null=True, default="None")
    error_date = models.DateTimeField(auto_now_add=True)


# Overriding Default Account Manager
class AccountManager(BaseUserManager):
    def create_user(
        self,
        email,
        username,
        data_nascimento,
        data_criacao,
        cpf,
        password=None,
    ):
        if not email:
            raise ValueError("Email obrigatorio")
        if not username:
            raise ValueError("Username obrigatorio")
        if not data_nascimento:
            raise ValueError("Data de nascimento obrigatoria")

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            data_nascimento=data_nascimento,
            data_criacao=data_criacao,
            cpf=cpf,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(
        self, email, username, data_nascimento, data_criacao, cpf, password
    ):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            password=password,
            data_nascimento=data_nascimento,
            data_criacao=data_criacao,
            cpf=cpf,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


#  Overriding Default Base User
class Account(AbstractBaseUser, PermissionsMixin):
    # Fields do usuario custom
    email = models.EmailField(
        verbose_name="email", max_length=150, unique=True, blank=False
    )
    username = models.CharField(max_length=30, unique=True, blank=False)
    cpf = models.CharField(max_length=14, unique=True, blank=False, null=True)
    data_nascimento = models.DateField(blank=False, null=True)
    data_criacao = models.DateTimeField(auto_now_add=True, blank=False, null=True)
    is_newsletter = models.BooleanField(default=False, null=False, blank=False)
    # Acount Manager aqui
    objects = AccountManager()

    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    # variavies cosntantes do novo BaseUserManager Model onde voce declara qual sera o username-field e fields
    # obrigatorios

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username", "data_nascimento", "cpf"]

    def __str__(self):
        return f"{self.username}"

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True
    
    def esconde_cpf(self):
        return "*" * 7 +  self.cpf[-5:-2] + '-' + self.cpf[-2] + self.cpf[-1]


class UserCart(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"{self.user.email}"

    class Meta:
        verbose_name_plural = "Carrinho Usuario"

    def calculate_total_price(self) -> float:
        total = 0
        for item in self.items.all():
            total += item.produto.preco * item.quantidade
        return total

    def calculate_total_price_real(self) -> float:
        total = (int(self.calculate_total_price()) / 100 )
        return total

class UserCartItems(models.Model):
    cart = models.ForeignKey(
        UserCart, 
        on_delete=models.CASCADE, 
        related_name="items")
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    quantidade = models.IntegerField(default=1)

    def total_price_items(self) -> float:
        return self.produto.preco * self.quantidade / 100

    class Meta:
        verbose_name_plural = 'Items Carrinho'

src/usuarios/forms.py
from django import forms
from usuarios.models import Atendimentos


class AtendimentoForm(forms.ModelForm):
    nome = forms.CharField(max_length=30,
                            min_length=3,
                            widget=forms.TextInput(attrs={
                                "class": "input-field",
                                "name": "nome",
                                "required": True,
                                "maxlength": "30",
                                "minlength": '3'
                              }))

    email = forms.EmailField(label='email', widget=forms.EmailInput(attrs={
        "class": "input-field",
        "required": True,
    })) 

    phone = forms.CharField(max_length=13,
                            min_length=11,
                            widget=forms.TextInput(attrs={
                                "class": "input-field",
                                "name": "phone",
                                "required": True,
                                "maxlength": 13,
                                "minlength": 11
                              }))
    
    assunto = forms.CharField(max_length=50,
                            min_length=5,
                            widget=forms.TextInput(attrs={
                                "class": "input-field",
                                "name": "assunto",
                                "required": True,
                                "maxlength": 50,
                                "minlength": 5,
                              }))
    message = forms.CharField(widget=forms.Textarea(attrs={
                            "name": "mensagem",
                            "rows": 6,
                            "cols": 30,
                            "class": "input-field",
    }))
    is_newsletter = forms.BooleanField(
                            required=False,
                            widget=forms.CheckboxInput(attrs={
                                "class": "check-box"
                            }),
                            initial=True,
                            )
    class Meta:
        model = Atendimentos
        fields = ['nome', 'email', 'phone', 'assunto', 'message', 'is_newsletter']

src/usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from usuarios import models
from .admin import UserCrerationForm as signup_form
from usuarios.forms import AtendimentoForm
from usuarios.mail import EnviaSigunupEmail
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from usuarios.models import UserCart, UserCartItems
from loja.models import Tosa, Banho, Produto
# Create your views here.

def login_view(request, *args, **kwargs):
    if request.user.is_authenticated:
        return redirect("usuarios:usuario")
    elif request.method == "POST":
        email = request.POST["email"]
        password = request.POST["password"]
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            return render(request, "usuarios/user.html", {
                "message": "Bem vindo de volta "
            })
        else:
            return render(
                request, "usuarios/login.html", {"message": "Email ou senha invalidos"}
            )
    return render(request, "usuarios/login.html", {})

@login_required
def login_sucess(request):
    if request.user.is_authenticated:
        return render(request, "usuarios/loginsucess.html")


def signup(request, *args, **kwargs):
    if request.method == "POST":
        form = signup_form(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data['email']
            password2 = form.cleaned_data['password2']
            username = form.cleaned_data['username']
            new_user = authenticate(request, email=email, password=password2)
            if new_user is not None:
                login(request, new_user)
                log = EnviaSigunupEmail(email=email, username=username)
                new_log = models.EmailErrorsLog()
                new_log.log = log
                new_log.email = email
                new_log.save()
                return redirect('usuarios:signupsucess')
        else:
            return render(request, "usuarios/signup.html", {"form": form})
    form = signup_form()
    context = {
        "form": form,  
        
    }
    return render(request, "usuarios/signup.html", context)

@login_required
def user_view(request):
    tosa_marcada = Tosa.objects.filter(user=request.user)
    banho_marcado = Banho.objects.filter(user=request.user)
    context = {
        'tosas': tosa_marcada,
        'banhos': banho_marcado
    }
    return render(request, "usuarios/user.html", context)

def signup_sucess_view(request):
    return render(request, "usuarios/signupsucess.html", {})

def logout_view(request):
    logout(request)
    return render(request, "index/index.html", {"message": "Deslogado com sucesso!"})


def atendimento(request, *args, **kwargs):
    if request.method == "POST":
        form = AtendimentoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("usuarios:atendimento-enviado")
        else:
            return render(request, "usuarios/atendimento.html")
    
    form = AtendimentoForm()
    
    return render(request, "usuarios/atendimento.html", {"form": form})


def atendimentoSubmited(request):
    return render(request, "usuarios/atendimentoSubmited.html", {})

def user_adress(request):
    return render(request, "usuarios/useradress.html")

@login_required
def cart_view(request):
    try:
        cart, created = UserCart.objects.get_or_create(user=request.user)
        cart_items = UserCartItems.objects.filter(cart=cart)
        items = cart_items.all()
        context = {'items': items, 'cart': cart}
    except UserCart.DoesNotExist:
        items = []
        context = {'items': items, 'cart': cart}

    return render(request, 'usuarios/cart.html', context)

src/usuarios/templates/usuarios/atendimento.html
{% extends 'index/base.html' %} {% block title %} Atendimento {% endblock %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'usuarios/style.css' %}">

<div class="atendimento-container">
  <h1 class="top-title">Atendimento</h1>
  <div class="information-container">
    <h4>
      Caso tenha alguma duvida ou algo pendente a ser resolvido preencha este
      formulario com suas informacoes que entraremos em contato.
    </h4>
    <br />
    <p>
      Aqui no Meu Melhor Amigo presamos nao so pelo seu pet mas pelo
      comprometimento com seus donos!
    </p>
    {% if form.errors %}
    <div class="message">
      <div class="alert alert-danger" style="margin-bottom: 70px;">
        {{ form.errors }}
      </div>
    </div>
    {% endif %}
  </div>
  <div class="atendimento-form-container">
    <form action="{% url 'usuarios:atendimento'%}" method="post">
      {% csrf_token %}
      <div class="input">
        {{ form.nome }}
        <label class="input-label" for="nome">
          <span>Nome</span>
        </label>
      </div>
      <div class="input">
        {{ form.email }}
        <label class="input-label" for="email"><span>Email</span></label>
      </div>
      <div class="input">
        {{ form.phone }}
        <label class="input-label" for="tel"><span>Telefone</span></label>
      </div>
      <div class="input">
      {{ form.assunto }}
        <label class="input-label" for="assunto"><span>Assunto</span></label>
      </div>
      <div class="input">
        {{ form.message }}
        <label class="input-label" for="mensagem"><span>Mensagem</span></label>
      </div>
      <div class="input">
        {{ form.is_newsletter }}
        <span>
          Deseja receber emails de newsletter?
        </span>
      </div>
      <button class="SubmitButton" type="submit">Enviar</button>
    </form>
  </div>
</div>
{% endblock %}

src/usuarios/templates/usuarios/atendimentoSubmited.html
{% extends 'index/base.html' %} {% block title %} Atendimento {% endblock %} 
{% block content %} {% load static %}
<link rel="stylesheet" href="{% static 'usuarios/style.css' %}" />
<div class="atendimento-container">
  <h1 class="top-title">Recebemos sua mensagem!</h1>
  <div class="atendimento-text-container">
    <div class="information-container">
      <div class="text">
        <h2>Dentro de momentos entraremos em contato via email.</h2>
        <br />
        <p>
          Lembramos que o horario de atendimento esta sujeito a feriados e ao
          periodo normal de funcionamento da loja. As respostas sao respondidas
          em ordem de recebimento caso sua mensagem nao seja respondida hoje
          fique tranquilo, ja iremos te responder. Normalmente respondemos no
          mesmo dia mas dependendo do horario e demanda atual pode demorar um
          pouco mais. O petshop Melhor Amigo agradece seu contato, tenha um bom
          dia!
        </p>
        <p>
          <br>
          Para o agendamento de banho e toza marque um horario ao clicar <a href=""> aqui</a>.
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

src/usuarios/templates/usuarios/atendimentosSubmited.html
{% extends 'usuarios/base.html' %} {% block title%} Atendimento  {% endblock %}
{% block content %}
<div class="atendimento-container">
    <h1 class="top-title">Recebemos sua mensagem!</h1>
    <div class="information-container">
      <h4>
        Dentro de momentos entraremos em contato via email.
        Para o agendamento de banho e toza marque um horario ao clicar em sobre Lavagem.  
      </h4>
      <br>
      <p>
        Lembramos que o horario de atendimento esta sujeito a feriados e ao periodo normal de funcionamento da loja.
        As respostas sao respondidas em ordem de recebimento caso sua mensagem nao seja respondida hoje fique tranquilo,
        ja iremos te responder. Normalmente respondemos no mesmo dia mas dependendo do horario e demanda atual pode demorar
        um pouco mais. O petshop Melhor Amigo agradece seu contato, tenha um bom dia!
      </p>
    </div>
{% endblock %}

src/usuarios/templates/usuarios/cart.html
{% extends 'index/base.html' %}
{% block title %} Carrinho {% endblock %}
{% block content %}

{% load static %}
{% load my_filters %}
<link rel="stylesheet" href="{% static 'usuarios/style.css' %}">
<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
<script>
    const decreaseButtons = document.querySelectorAll('.decreaseButton');
      const increaseButtons = document.querySelectorAll('.increaseButton');
      const quantitySelectors = document.querySelectorAll('.quantidadeSelect');
  
      decreaseButtons.forEach((button, index) => {
          button.addEventListener('click', () => {
              const currentValue = parseInt(quantitySelectors[index].value);
              if (currentValue > 1) {
                  quantitySelectors[index].value = (currentValue - 1).toString();
              }
          });
      });
  
      increaseButtons.forEach((button, index) => {
          button.addEventListener('click', () => {
              const currentValue = parseInt(quantitySelectors[index].value);
              quantitySelectors[index].value = (currentValue + 1).toString();
          });
      });
  </script>

<div class="cart-container">
    <div class="cart-user-container">
        <h1 class="username">Carrinho de {{ request.user }}</h1>
        {% if items %}
        <div class="items">
            <section>
                <table> <!-- Criando a tabela do carrinho front User-->
                    <thead> <!-- Cabeçalho da tabela do carrinho front User-->
                        <tr> <!-- Sub-Titulos da tabela, carrinho front user-->
                            <th>Produtos</th>
                            <th>Preço</th>
                            <th>Quantidade</th>
                            <th>Total</th>
                        </tr>
                        {% for item in items %}
                            {% if item.quantidade > 0 %}
                            </thead>
                                <tbody>
                                <tr>
                                    <td>
                                        <div class="product">
                                            <img src="{{ item.produto.img.url }}" alt="{{ item.produto.nome }}" class="imgcel">
                                            <div class="info">
                                                <div class="nomeproduto">{{ item.produto.nome }}</div>
                                                <div class="categoria">{{ item.produto.category }}</div>
                                            </div>
                                        </div>
                                    </td>
                        <td>R${{ item.produto.preco_em_real }} </td>
                        <td>
                            <div class="qntd">
                                <form  method="post" action="{% url 'loja:remove-cart' item.produto.id %}">
                                    {% csrf_token %}
                                    <button id="decreaseButton" type="submit">-</button>
                                </form>
                                <span>{{ item.quantidade }}</span>
                                <form method="post" action="{% url 'loja:add-cart' item.produto.id %}">
                                    {% csrf_token %}
                                    <button id="increaseButton" type="submit">+</button>
                                </form>
                            </div>
                        </td>
                        <td>R${{ item.total_price_items }}</td>
                        <td class="removeitem">
                            <form method="post" action="{% url 'loja:remove-all-cart' item.produto.id %}">
                                {% csrf_token %}
                                <button class="deleteitem" type="submit"><i class='bx bxs-trash'></i></button>
                            </form>
                        </td>
                    </tr>
                    
                    {% endif %}
                    {% endfor %}
                    </tbody>
                </table>
            </section>
            <aside>
                <div class="box">
                    <header>Resumo da Compra</header>
                    <div class="info">
                        <div><span>Sub-Total</span><span></span>R${{ cart.calculate_total_price_real }}</div>
                        <div><span>Frete</span><span></span>Gratuito</div>
                    </div>
                    <footer>
                        <span>Total</span>
                        <span>R${{ cart.calculate_total_price_real }}</span>
                    </footer>
                </div>{% if cart.calculate_total_price_real != 0 %}
                <a href="">
                    <button type="submit">Checkout</button>
                </a>
                    {% else %}
            <a href="{% url 'loja:loja' %}">
            <button class="btn btn-success"> Shop
            </button>
        </a> 
        {% endif %}
    </aside>
 
                    {% if cart.calculate_total_price_real == 0 %}
                    <div class="items">
                        <h1>Nenhum item no carrinho</h1>
                    </div>
                    {% endif %}            
        </div>
                    {% else %}
                    <div class="items">
                    <h1>Nenhum item no carrinho</h1>
                    </div>
                    {% endif %}


    </div>
</div>

{% endblock %}

src/usuarios/templates/usuarios/login.html
{% extends 'index/base.html' %} {%block title%} Login {%endblock%} 
{% block content %} 

<div class="atendimento-container">
  {% if message %}
  <div class="alert alert-danger">{{message}}</div>
  {% endif %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'usuarios/style.css' %}">
  <h1 class="top-title">Login</h1>
  <div class="information-container">
    <h4>Para logar entre com email <br> </h4>
    <p>Caso nao tenha uma conta crie clicando abaixo</p>
  </div>  
  <div class="atendimento-form-container">
      <form action="{% url 'usuarios:login' %}" method="POST">
          {% csrf_token %}
        <div class="input">
            <input type="email" name="email" maxlength="150" required class="input-field"/>
            <label for="email" class="input-label"><span>Email</span></label>
        </div>
        <div class="input">
            <input 
            type="password"
            name="password"
            maxlength="50"
            minlength="8"
            required
            class="input-field"
            />
            <label for="password" class="input-label"><span>Password</span></label>
        </div>
            <input type="submit" value="Login" class="SubmitButton">
            <p>Dont have account?<a href="{% url 'usuarios:signup' %}"><i class="fa-solid fa-user-plus"></i></a></p>
        </form>
    </div>
</div>
{% endblock %}

src/usuarios/templates/usuarios/signup.html
{% extends 'index/base.html' %} {% block title %} signup {% endblock %} 

{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static 'usuarios/style.css' %}">
<div class="atendimento-container">
  <h1 class="top-title">Cadastro</h1>
  <div class="information-container">
    <h4>Para se cadastrar na plataforma preencha o formulario abaixo: <br> </h4>
  </div>  
  <div class="atendimento-form-container">
    {% if form.errors %}
    <div class="message">
      <div class="alert alert-danger" style="margin-bottom: 70px;">
        {{ form.errors }}
      </div>
    </div>
    {% endif %}
    <form action="{% url 'usuarios:signup' %}" method="POST">
      {% csrf_token %}
      <div class="input">
        {{ form.email }}
        <label class="input-label" for="email">
          <span>Email</span>
        </label>
      </div>
      <div class="input">
        {{ form.username }}
        <label class="input-label" for="username">
          <span>
            Nome
          </span>
      </label>
      </div>
      <div class="input">
        {{ form.password1 }}
        <label class="input-label" for="password1"><span>
          Senha</span>
        </label>
      </div>
      <div class="input">
        {{ form.password2 }}
        <label class="input-label" for="password2">
          <span>Confirmacao de senha</span>
        </label>
      </div>
      <div class="input">
        <label  for="data_nascimento"><span>
          Data de Nascimento:</span>
        </label>
        {{ form.data_nascimento }}
      </div>
      <div class="input">
        {{ form.cpf }}
        <label class="input-label" for="cpf">cpf</label>
      </div>
      <div class="input">
        {{ form.is_newsletter }}
        <label for="is_newsletter"> Deseja assinar newsletter?</label>
      </div>
      <input class="SubmitButton" type="submit" value="cadastrar">
    </form>
  </div>
</div>
</form>

{% endblock %}

src/usuarios/templates/usuarios/signup2.html
{% extends 'index/base.html' %}

src/usuarios/templates/usuarios/singup.html
{% extends 'index/base.html' %} {% block title %} signup {% endblock %} 

{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static 'usuarios/style.css' %}">
<div class="atendimento-container">
  <div class="atendimento-form-container">
    <form action="{% url 'usuarios:signup' %}" method="POST">
      {% csrf_token %}
      <div class="input">
        {{ form.email }}
        <label class="input-label" for="email">
          <span>Email</span>
        </label>
      </div>
      <div class="input">
        {{ form.username }}
        <label class="input-label" for="username">
          <span>
            Username
          </span>
      </label>
      </div>
      <div class="input">
        {{ form.password1 }}
        <label class="input-label" for="password1"><span>
          Password</span>
        </label>
      </div>
      <div class="input">
        {{ form.data_nascimento }}
        <label class="input-label" for="data_nascimento"><span>
          Date of Birth</span>
        </label>
      </div>
      <div class="input">
        {{ form.password2 }}
        <label class="input-label" for="password2">
          <span>Password Confirmation</span>
        </label>
      </div>
      <div class="input">
        {{ form.cpf }}
        <label class="input-label" for="cpf">Cpf</label>
      </div>
      <input class="SubmitButton" type="submit" value="cadastrar">
    </form>
  </div>
</div>
  
  <!-- 
  <input type="text" name="name" minlength="3" maxlength="25" required />
  <label for="name">Nome</label>

  <input type="email" name="email" maxlength="150" required />
  <label for="email">Email</label>

  <input
    type="password"
    name="password"
    maxlength="50"
    minlength="8"
    required
  />
  <label for="password">password</label>

  <input
    type="text"
    name="cpf"
    maxlength="14"
    minlength="11"
    pattern="\d{3}.?\d{3}.?\d{3}-?\d{2}"
    required
  />
  <label for="cpf">Cpf</label>

  <input type="date" name="data_nascimento" />
  <label for="date">Data nascimento</label>

  <input type="button" value="enviar" />-->
</form>

{% endblock %}

src/usuarios/templates/usuarios/user.html
{% extends 'index/base.html' %}
{% block title %} Melhor Amigo {{ request.user.username }} {% endblock %} 
{% block content %} {% load static %}

<link rel="stylesheet" href="{% static 'usuarios/style.css' %}" />
<style>
  h1 {
    margin-top: 10px;
    margin-bottom: 5vh;
  }
  .accordion {
    margin-top: 20px;
    margin-bottom: 15vh;
  }
  a{
    text-decoration: none;
    font-size: 15px;
  }
  .fa-lock{
    color: greenyellow;
    font-size: 20px;
    margin-left: 9px;
    transition: 0.5s;
  }
</style>
<div class="form-container">
  {% if message %}
  <div class="alert alert-success">
    {{ message }} {{ request.user.username }}
  </div>
  {% endif %}
  <h1>Ola, {{ request.user.username }}!</h1>
  <div class="content">
    <div class="accordion" id="accordionExample">
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button
            class="accordion-button"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#collapseOne"
            aria-expanded="true"
            aria-controls="collapseOne"
          >
            <h4>
                Dados Pessoais
            </h4>
          </button>
        </h2>
        <div
          id="collapseOne"
          class="accordion-collapse collapse"
          data-bs-parent="#accordionExample"
        >
          <div class="accordion-body">
            <p>
            Nome: <strong>{{ request.user.username }}</strong> <br />
            Email: <strong>{{ request.user.email }}</strong> <br />
            Cpf: <strong>{{ request.user.esconde_cpf}}</strong> <br />
            Data Nasimento: <strong>{{ request.user.data_nascimento }}</strong> <br />
            {% if request.user.is_admin == True %}
            <span>Admin Panel<a href="http://127.0.0.1:8000/admin/"><i class="fa-solid fa-lock"></i></a></span> <br />
            {% endif %}
            Conosco Desde: <strong> {{ request.user.data_criacao }} </strong>
            </p>
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button
            class="accordion-button collapsed"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#collapseTwo"
            aria-expanded="false"
            aria-controls="collapseTwo"
          >
           <h4>Tosa e Banho</h4>
          </button>
        </h2>
        <div
          id="collapseTwo"
          class="accordion-collapse collapse"
          data-bs-parent="#accordionExample"
        >
          <div class="accordion-body">
              {% if tosas %}
                {% for tosa in tosas %}
                <p>
                  <strong>TOSA</strong> Data: {{ tosa.data }} - Para: {{ tosa.pet }} - R${{ tosa.type.preco }} 
                </p> <br>

                {% endfor %}
              {% else %}
                <p>Nenhuma Tosa marcada</p>
            {% endif %}
            {% if banhos %}
              {% for banho in banhos %}
                <p>
                  <strong>BANHO</strong> Data: {{ banho.data }} - Para: {{ banho.pet }} - R${{ banho.type.preco }} 
                </p>
              {% endfor %}
            {% else %}
              <p> Nenhum Banho marcado </p>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
    <div>
      <a class="btn btn-danger" href="{% url 'usuarios:logout' %}">Logout</a>
    </div>
  </div>
</div>

{% endblock %}